const KEYS = [
    {label: 'A Major', value: 'a'},
    {label: 'A Sharp Major', value: 'a-sharp'},
    {label: 'B Flat Major', value: 'b-flat'},
    {label: 'B Major', value: 'b'},
    {label: 'C Major', value: 'c'},
    {label: 'C Sharp Major', value: 'c-sharp'},
    {label: 'D Flat Major', value: 'd-flat'},
    {label: 'D Major', value: 'd'},
    {label: 'D Sharp Major', value: 'd-sharp'},
    {label: 'E Flat Major', value: 'e-flat'},
    {label: 'E Major', value: 'e'},
    {label: 'F Major', value: 'f'},
    {label: 'F Sharp Major', value: 'f-sharp'},
    {label: 'G Flat Major', value: 'g-flat'},
    {label: 'G Major', value: 'g'},
    {label: 'G Sharp Major', value: 'g-sharp'},
    {label: 'A Flat Major', value: 'a-flat'},
    {label: 'A Minor', value: 'a-minor'},
    {label: 'A Sharp Minor', value: 'a-sharp-minor'},
    {label: 'B Flat Minor', value: 'b-flat-minor'},
    {label: 'B Minor', value: 'b-minor'},
    {label: 'C Minor', value: 'c-minor'},
    {label: 'C Sharp Minor', value: 'c-sharp-minor'},
    {label: 'D Flat Minor', value: 'd-flat-minor'},
    {label: 'D Minor', value: 'd-minor'},
    {label: 'D Sharp Minor', value: 'd-sharp-minor'},
    {label: 'E Flat Minor', value: 'e-flat-minor'},
    {label: 'E Minor', value: 'e-minor'},
    {label: 'F Minor', value: 'f-minor'},
    {label: 'F Sharp Minor', value: 'f-sharp-minor'},
    {label: 'G Flat Minor', value: 'g-flat-minor'},
    {label: 'G Minor', value: 'g-minor'},
    {label: 'G Sharp Minor', value: 'g-sharp-minor'},
    {label: 'A Flat Minor', value: 'a-flat-minor'},
]

export default KEYS;