const KEYS = [
    {label: 'A Major', value: 'a'},
    {label: 'B Flat Major', value: 'b-flat'},
    {label: 'B Major', value: 'b'},
    {label: 'C Major', value: 'c'},
    {label: 'D Flat Major', value: 'd-flat'},
    {label: 'D Major', value: 'd'},
    {label: 'E Flat Major', value: 'e-flat'},
    {label: 'E Major', value: 'e'},
    {label: 'F Major', value: 'f'},
    {label: 'G Flat Major', value: 'g-flat'},
    {label: 'G Major', value: 'g'},
    {label: 'A Flat Major', value: 'a-flat'},
    {label: 'A Minor', value: 'a-minor'},
    {label: 'B Flat Minor', value: 'b-flat-minor'},
    {label: 'B Minor', value: 'b-minor'},
    {label: 'C Minor', value: 'c-minor'},
    {label: 'D Flat Minor', value: 'd-flat-minor'},
    {label: 'D Minor', value: 'd-minor'},
    {label: 'E Flat Minor', value: 'e-flat-minor'},
    {label: 'E Minor', value: 'e-minor'},
    {label: 'F Minor', value: 'f-minor'},
    {label: 'G Flat Minor', value: 'g-flat-minor'},
    {label: 'G Minor', value: 'g-minor'},
    {label: 'A Flat Minor', value: 'a-flat-minor'},
]

export default KEYS;