services: 
  web:
    build:
      dockerfile: docker/web/Dockerfile
      context: .
    image: web:latest
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb?schema=public
      - DIRECT_URL=postgresql://user:password@db:5432/mydb?schema=public
    depends_on:
      db:
        condition: service_healthy
  db:
    build:
      dockerfile: docker/db/Dockerfile
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: